package ankhangbo.fabricloader.asm;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.InsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.VarInsnNode;

import java.lang.instrument.ClassFileTransformer;
import java.security.ProtectionDomain;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Leaf's own equivalent of {@link PaperclipDelegationTransformer} — Leaf (Winds-Studio/Leaf)
 * does NOT use upstream io.papermc.paperclip.Paperclip as its bootstrap jar. Its
 * {@code leaf-server/build.gradle.kts.patch} swaps the {@code paperclip(...)} dependency for
 * Leaf's own fork, published as {@code cn.dreeam:quantumleaper} (source:
 * github.com/Winds-Studio/QuantumLeaper), whose entry class is
 * {@code cn.dreeam.leaper.QuantumLeaper}.
 *
 * <p>That fork is itself derived from upstream Paperclip and keeps the exact same private static
 * method shapes this project already relies on — {@code setupClasspath(): URL[]} and
 * {@code findMainClass(): String} — so nothing about {@link ankhangbo.fabricloader.Pclip}'s own
 * classpath/ASM/server-jar-detection logic needs to differ between Paper and Leaf; only the
 * bootstrap class name being patched (and reflectively invoked from) differs. See
 * {@code Pclip.run(String, String[])}, which both this class and
 * {@link PaperclipDelegationTransformer} ultimately delegate into, just via two different
 * ASM-callable entry points ({@code Pclip.mainLeaf} here vs. {@code Pclip.main} there) so the
 * generated bytecode below never needs to embed a dynamic class-name constant.
 *
 * <p>Registered via {@code inst.addTransformer(new LeafclipDelegationTransformer(), false)}
 * alongside {@link PaperclipDelegationTransformer} in {@code FabricLoaderAgent.premain()} — only
 * one of the two target classes will ever actually be present on a given server's classpath
 * (Paper ships Paperclip, Leaf ships QuantumLeaper instead), so both transformers can safely stay
 * registered at once: whichever one doesn't match a given class's name simply returns {@code
 * null} (no-op) for it, same as this class does below for every class that isn't its own target.
 */
public final class LeafclipDelegationTransformer implements ClassFileTransformer {

    private static final Logger LOGGER = Logger.getLogger("ankhangbo.fabricloader.LeafclipDelegationTransformer");
    private static final String TARGET = "cn/dreeam/leaper/QuantumLeaper";

    @Override
    public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined,
                             ProtectionDomain protectionDomain, byte[] classfileBuffer) {
        if (!TARGET.equals(className)) {
            return null;
        }
        try {
            return patch(classfileBuffer);
        } catch (Throwable t) {
            LOGGER.log(Level.SEVERE, "Failed to patch cn.dreeam.leaper.QuantumLeaper for Pclip "
                    + "delegation — falling back to STOCK QuantumLeaper behavior this run (Leaf "
                    + "will boot the old way, real Fabric Loader will NOT be used)", t);
            return null;
        }
    }

    private static byte[] patch(byte[] original) {
        ClassReader reader = new ClassReader(original);
        ClassNode classNode = new ClassNode();
        reader.accept(classNode, 0);

        boolean rewroteMain = false;
        for (MethodNode method : classNode.methods) {
            switch (method.name) {
                case "main":
                    if ("([Ljava/lang/String;)V".equals(method.desc)) {
                        replaceMainBody(method);
                        rewroteMain = true;
                    }
                    break;
                case "setupClasspath":
                case "findMainClass":
                    widenToPublic(method);
                    break;
                default:
                    break;
            }
        }

        if (!rewroteMain) {
            throw new IllegalStateException("Did not find QuantumLeaper.main(String[]) to rewrite "
                    + "— Leaf's paperclip fork's internal layout changed since this transformer "
                    + "was written");
        }

        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        classNode.accept(writer);
        LOGGER.info("LeafclipDelegationTransformer installed - waiting for "
                + "cn.dreeam.leaper.QuantumLeaper to load.");
        return writer.toByteArray();
    }

    /** Empties main()'s body and replaces it with: Pclip.mainLeaf(args); return; */
    private static void replaceMainBody(MethodNode method) {
        InsnList newInsns = new InsnList();
        newInsns.add(new VarInsnNode(Opcodes.ALOAD, 0)); // args
        newInsns.add(new MethodInsnNode(
                Opcodes.INVOKESTATIC,
                "ankhangbo/fabricloader/Pclip",
                "mainLeaf",
                "([Ljava/lang/String;)V",
                false));
        newInsns.add(new InsnNode(Opcodes.RETURN));

        method.instructions.clear();
        method.tryCatchBlocks.clear();
        method.instructions.add(newInsns);
    }

    private static void widenToPublic(MethodNode method) {
        method.access = (method.access & ~(Opcodes.ACC_PRIVATE | Opcodes.ACC_PROTECTED))
                | Opcodes.ACC_PUBLIC;
    }
}
