package ankhangbo.fabricloader.asm;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.MethodNode;

import java.lang.instrument.ClassFileTransformer;
import java.security.ProtectionDomain;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Leaf/Paper/Moonrise make many vanilla methods {@code final} (e.g. {@code Vec3i#equals/hashCode/getX/getY/getZ}, {@code Level#getEntitiesOfClass})
 * (vanilla / Fabric servers do not). Mods written against vanilla override them - e.g. Create Fly's
 * {@code TrackNodeLocation extends Vec3i} overrides {@code equals} and {@code hashCode} - and the JVM then refuses to
 * define the subclass: {@code IncompatibleClassChangeError: class ... overrides final method Vec3i.equals(Object)}.
 *
 * <p>Fix: drop ACC_FINAL from those methods (see {@link #TARGETS}: ~220 methods in ~55 classes, e.g. Vec3i, Entity, Level, BucketItem). Only a flag changes (no code, no frames); behaviour of the
 * existing implementation is untouched, subclasses that do not override them are not affected.
 * Disable with {@code -Dankhangbo.vec3iUnfinal=false}.
 */
public final class Vec3iUnfinalTransformer implements ClassFileTransformer {
	private static final Logger LOGGER = Logger.getLogger("ankhangbo.fabricloader.asm.Vec3iUnfinalTransformer");
	private static final boolean ENABLED = !"false".equalsIgnoreCase(System.getProperty("ankhangbo.vec3iUnfinal"));

	/**
	 * class -> method names that Leaf made final but a vanilla/Fabric server leaves overridable. Generated by diffing the Leaf
	 * and Fabric server sources: every non-static, non-private method declared {@code final} in Leaf and not {@code final} in
	 * the Fabric server (that includes methods Leaf re-declares as final although Fabric only inherits them, e.g.
	 * {@code Level#getEntitiesOfClass}). Matched by name only, so every overload of a name is un-finalised (harmless).
	 * More can be added without rebuilding: {@code -Dankhangbo.unfinal=net/minecraft/x/Y#method,net/minecraft/a/B#other}.
	 */
	private static final Map<String, Set<String>> TARGETS = new HashMap<>();

	private static void add(String cls, String names) {
		TARGETS.computeIfAbsent(cls, k -> new HashSet<>()).addAll(Arrays.asList(names.split(",")));
	}

	static {
		add("net/minecraft/core/SectionPos", "minBlockX,minBlockY,minBlockZ");
		add("net/minecraft/core/Vec3i", "equals,getX,getY,getZ,hashCode,isInsideBuildHeightAndWorldBoundsHorizontal");
		add("net/minecraft/network/Connection", "getPlayer");
		add("net/minecraft/network/PacketProcessor", "executeSinglePacket");
		add("net/minecraft/server/MinecraftServer", "executeMidTickTasks,hasStopped,issueEmergencySave,setChunkSystemCrash");
		add("net/minecraft/server/level/ChunkHolder", "addReceivedChunk,getFullChunk,getPlayers,getRealChunkHolder,getTickingChunk,hasChunkBeenSent,removeReceivedChunk,setRealChunkHolder");
		add("net/minecraft/server/level/ChunkMap", "getUnloadingChunkHolder");
		add("net/minecraft/server/level/DistanceManager", "addPlayer,getChunkHolderManager,hasAnyNearbyNarrow,removePlayer,updatePlayer");
		add("net/minecraft/server/level/ServerChunkCache", "getFullChunkIfLoaded,setFullChunk");
		add("net/minecraft/server/level/ServerLevel", "addPlayerTickingRequest,areChunksLoaded,areChunksLoadedForEntityMove,areChunksLoadedForMove,getAnyChunkIfLoaded,getChunkDataController,getChunkTaskScheduler,getEntityChunkDataController,getEntityTickingChunks,getFullChunkIfLoaded,getLastMidTickFailure,getLoadedChunks,getNearbyPlayers,getPlayerChunkLoader,getPlayerTickingChunks,getPoiChunkDataController,getRegionChunkShift,getSpecificChunkIfLoaded,getTickingChunks,getViewDistanceHolder,issueEmergencySave,loadChunks,loadChunksAsync,loadChunksForMoveAsync,markChunkForPlayerTicking,midTickTasks,removeChunkForPlayerTicking,removePlayerTickingRequest,setLastMidTickFailure,syncLoadNonFull");
		add("net/minecraft/server/level/ServerPlayer", "getChunkLoader,getViewDistanceHolder,isRealPlayer,setChunkLoader,setRealPlayer");
		add("net/minecraft/server/level/ThreadedLevelLightEngine", "serverRelightChunks");
		add("net/minecraft/server/level/Ticket", "compareTo,getIdentifier,getRemoveDelay,setIdentifier,setRemoveDelay");
		add("net/minecraft/server/level/WorldGenRegion", "getBlockStateIfLoaded,getFluidIfLoaded");
		add("net/minecraft/server/network/ServerCommonPacketListenerImpl", "disconnectAsync");
		add("net/minecraft/server/network/ServerGamePacketListenerImpl", "isDisconnected");
		add("net/minecraft/util/CrudeIncrementalIntIdentityHashBiMap", "getRawPalette");
		add("net/minecraft/util/SimpleBitStorage", "countEntries,get,getAndSet,set");
		add("net/minecraft/util/SortedArraySet", "copy,removeAndGet,removeIf,replace");
		add("net/minecraft/util/ZeroBitStorage", "countEntries,get,getAndSet,set");
		add("net/minecraft/util/thread/BlockableEventLoop", "executeAllRecentInternalTasks");
		add("net/minecraft/world/entity/Entity", "collidedWithShapeMovingFrom,detectDespawnTime,distanceTo,distanceToSqr,getBoundingBoxAt,getChunkData,getChunkStatus,getSectionX,getSectionY,getSectionZ,getTrackedEntity,hasAnyPlayerPassengers,isExceedingDespawnTime,isHardColliding,isUpdatingSectionStatus,registerScheduler,retireScheduler,setChunkData,setChunkStatus,setSectionX,setSectionY,setSectionZ,setTrackedEntity,setUpdatingSectionStatus,teleportTo");
		add("net/minecraft/world/entity/EntityType", "isAllowedInPeaceful");
		add("net/minecraft/world/entity/LivingEntity", "drop");
		add("net/minecraft/world/entity/ai/village/poi/PoiManager", "checkConsistency,getWorld,loadInPoiChunk,onUnload");
		add("net/minecraft/world/entity/ai/village/poi/PoiSection", "asOptional,isEmpty");
		add("net/minecraft/world/inventory/AbstractContainerMenu", "createBlockHolder,getTitle,setTitle");
		add("net/minecraft/world/item/BucketItem", "emptyContents");
		add("net/minecraft/world/level/Level", "checkEntityCollision,getBlockStateIfLoaded,getBlockStateIfLoadedAndInBounds,getBlockStateIfLoadedUnchecked,getChunk,getChunkAt,getChunkAtIfLoadedUnchecked,getChunkData,getChunkIfLoaded,getChunkIfLoadedImmediately,getEntitiesOfClass,getEntityCount,getEntityLookup,getFluidIfLoaded,getFluidStateIfLoadedUnchecked,getHardCollidingEntities,hasChunkAt,isLoadedAndInBounds,releaseChunkData,requestChunkData,setEntityLookup");
		add("net/minecraft/world/level/PathNavigationRegion", "getBlockStateIfLoaded,getFluidIfLoaded");
		add("net/minecraft/world/level/TicketStorage", "getChunkMap,setChunkMap");
		add("net/minecraft/world/level/block/Block", "isDestroyable");
		add("net/minecraft/world/level/block/entity/BlockEntity", "applyComponentsSet");
		add("net/minecraft/world/level/block/state/BlockState", "getBukkitMaterial");
		add("net/minecraft/world/level/block/state/StateHolder", "getTableIndex,init");
		add("net/minecraft/world/level/block/state/properties/Property", "getById,getId,setById");
		add("net/minecraft/world/level/chunk/ImposterProtoChunk", "getBlockState");
		add("net/minecraft/world/level/chunk/LevelChunk", "getBlock,getBlockStateIfLoaded,getChunkHolder,getFluidIfLoaded,isPostProcessingDone,setChunkHolder,shouldDoLightning");
		add("net/minecraft/world/level/chunk/LevelChunkSection", "getTickingBlockList,hasSpecialCollidingBlocks");
		add("net/minecraft/world/level/chunk/LinearPalette", "getRawPalette");
		add("net/minecraft/world/level/chunk/PalettedContainer", "get,getData");
		add("net/minecraft/world/level/chunk/ProtoChunk", "getBlockStateIfLoaded,getFluidIfLoaded");
		add("net/minecraft/world/level/chunk/SingleValuePalette", "getRawPalette");
		add("net/minecraft/world/level/chunk/status/ChunkStatus", "getNextStatus,getWarnedAboutNoImmediateComplete,getWriteRadius,isEmptyGenStatus,isEmptyLoadStatus,isParallelCapable,setParallelCapable,setWriteRadius");
		add("net/minecraft/world/level/chunk/storage/RegionBitmap", "copyFrom,tryAllocate");
		add("net/minecraft/world/level/chunk/storage/RegionFile", "startWrite");
		add("net/minecraft/world/level/chunk/storage/RegionFileStorage", "doesRegionFileNotExistNoIO,finishRead,finishWrite,getRegionFileIfExists,getRegionFileIfLoaded,readData,startWrite");
		add("net/minecraft/world/level/chunk/storage/SectionStorage", "getRegionStorage");
		add("net/minecraft/world/level/chunk/storage/SimpleRegionStorage", "getRegionStorage");
		add("net/minecraft/world/level/levelgen/Heightmap", "isOpaque");
		add("net/minecraft/world/level/lighting/LevelLightEngine", "getLightEngine");
		add("net/minecraft/world/phys/AABB", "collidedAlongVector,offsetY");
		add("net/minecraft/world/phys/shapes/DiscreteVoxelShape", "getOrCreateCachedShapeData");
		add("net/minecraft/world/phys/shapes/VoxelShape", "getCachedVoxelData,getFaceShapeClamped,getSingleAABBRepresentation,initCache,isFullBlock,occludesFullBlock,occludesFullBlockIfCached,offsetX,offsetY,offsetZ,orUnoptimized,rootCoordinatesX,rootCoordinatesY,rootCoordinatesZ");
		add("net/minecraft/world/ticks/LevelChunkTicks", "clearDirty,isDirty");

		for (String e : System.getProperty("ankhangbo.unfinal", "").split(",")) {
			int h = e.indexOf('#');

			if (h > 0) add(e.substring(0, h).trim().replace('.', '/'), e.substring(h + 1).trim());
		}
	}

	@Override
	@SuppressWarnings("unchecked")
	public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined,
			ProtectionDomain protectionDomain, byte[] classfileBuffer) {
		if (!ENABLED) return null;

		Set<String> names = TARGETS.get(className);

		if (names == null) return null;

		try {
			ClassNode cn = new ClassNode();
			new ClassReader(classfileBuffer).accept(cn, 0);

			int changed = 0;

			for (MethodNode m : (List<MethodNode>) cn.methods) {
				if ((m.access & Opcodes.ACC_FINAL) != 0 && (m.access & Opcodes.ACC_STATIC) == 0 && names.contains(m.name)) {
					m.access &= ~Opcodes.ACC_FINAL;
					changed++;
				}
			}

			if (changed == 0) return null;

			ClassWriter w = new ClassWriter(ClassWriter.COMPUTE_MAXS);
			cn.accept(w);
			LOGGER.info("PATCHED " + className + " (removed final from " + changed + " method(s) that mods written for vanilla/Fabric override)");
			return w.toByteArray();
		} catch (Throwable t) {
			LOGGER.log(Level.WARNING, "Failed to patch " + className, t);
			return null;
		}
	}
}
